In [85]:
import numpy as np
import pandas as pd
data = pd.read_csv('appartment_ave_prices.csv', sep = ';')
data

,Год,Все типы квартир,Квартиры низкого качества,Квартиры среднего качества (типовые),Квартиры улучшенного качества,Элитные квартиры
0,1998,4941,3943,4431,5400,8247
1,1999,6151,4548,5371,6605,12130
2,2000,6590,5483,6422,7422,12009
3,2001,9072,7152,8789,9927,15476
4,2002,11557,9183,11254,12467,16663
5,2003,13967,12004,13659,14720,22906
6,2004,17931,15457,17911,18929,30405
7,2005,22166,19247,21915,23486,34995
8,2006,36615,32961,36198,38616,67979
9,2007,47206,40589,44630,48383,71549
10,2008,56495,50010,53752,57506,83207
11,2009,52895,48439,48940,53956,88140
12,2010,59998,54203,56762,60814,105302
13,2011,48243,42368,44002,50858,73168
14,2012,56370,48102,51279,60847,84525
15,2013,56478,49289,51419,60738,97811
16,2014,58085,51584,52664,62288,99261
17,2015,56283,49769,51574,60347,85084
18,2016,53983,45149,49359,59051,75256
19,2017,52350,42486,48159,57673,75032
20,2018,54924,47050,51157,59248,78245
21,2019,58528,49122,53864,63117,84334
22,2020,66712,52569,61020,72486,103043

In [86]:
test_arr = data["Все типы квартир"]
test_value = test_arr[22]
data = data.drop([0, 1, 2, 3, 4, 5, 22], axis = 0)
X = data["Год"]
X.index = np.arange(1, len(X) + 1)
for i in range(1,17):
    X = X.replace({X[i]: i})
Y = data["Все типы квартир"]
Y.index = np.arange(1, len(Y) + 1)

In [87]:
X # массив времени

1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
Name: Год, dtype: int64

In [88]:
Y # массив цен

1     17931
2     22166
3     36615
4     47206
5     56495
6     52895
7     59998
8     48243
9     56370
10    56478
11    58085
12    56283
13    53983
14    52350
15    54924
16    58528
Name: Все типы квартир, dtype: int64

In [100]:
if X.size == Y.size:
    n = X.size

Yf_X = Y * X

X2 = X ** 2

a = (sum(Yf_X) - (sum(X) * sum(Y)) / n) / (sum(X2) - (sum(X)**2)/n)

b = sum(Y) / n - a *sum(X) / n

predict = a * (n+1) + b
error_mnk = (1 - predict / test_value)*100
print('Прогноз на 2020 год по МНК: ',predict)
print('Фактическое значение за 2020 год: ',test_value)
print('Погрешность: ',error_mnk, '%')

Прогноз на 2020 год по МНК:  65420.875
Фактическое значение за 2020 год:  66712
Погрешность:  1.9353714474157568 %

In [101]:
def s(x, w, z):
    med = (Y[x] + Y[w] + Y[z])/3
    return med

ave_values = [0]
for i in range(2,16):
    ave_values.append(s(i-1, i, i+1))
ave_values.append(0)
ave_values

[0,
 25570.666666666668,
 35329.0,
 46772.0,
 52198.666666666664,
 56462.666666666664,
 53712.0,
 54870.333333333336,
 53697.0,
 56977.666666666664,
 56948.666666666664,
 56117.0,
 54205.333333333336,
 53752.333333333336,
 55267.333333333336,
 0]

In [103]:
pred = ave_values[14] + 1/3 * (Y[16] - Y[15])
error_mss = (1 - pred / test_value)*100
print('Прогноз на 2020 год по МСС:', pred)
print('Фактическое значение за 2020 год: ',test_value)
print('Погрешность: ', error_mss, '%')
print('МНК оказался эффективнее в ', error_mss/error_mnk, 'раз')

Прогноз на 2020 год по МСС: 56468.66666666667
Фактическое значение за 2020 год:  66712
Погрешность:  15.354558899948023 %
МНК оказался эффективнее в  7.933649594991444 раз